### PR TITLE
Adds tester button and function to remove markers added by search

### LINKED ISSUE #29: Undo functionality for added markers

### PR DESCRIPTION
**Pull request by ClareBee**
resolves #29
Hi there,
So the functionality works ok - have added a temporary button just to show that - but let me know if you can think of a better way to do it!
We can then discuss tomorrow if we want it just to be a one-off undo option (which currently works) or whether we want to be more specific.
We also need to decide how it's triggered....
Have duplicated the add marker function as the easiest way to differentiate between the two types of marker = prepopulated or user-added,  as they end up in different arrays in the constructor.

### CODE REVIEW

**Comment by PMGH** [comment]
Just something to consider for when we go round to refactor:

Instead of duplicating the createMarker function we can probably use square bracket notation to handle which array the new marker gets pushed into? E.g. this.[markers].push(marker);    or    this.[newMarkers].push(newMarker);     

The array name could just be passed into the function as an argument in string form (I think), like:
this.createMarker(place, icon, "markers")     or:
this.createMarker(place, icon, "newMarkers")

**Comment by ClareBee** [comment]
Yes - agreed that we want to avoid duplicating. I wasn't sure how to differentiate between prepopulated markers and ones added through the search bar, but if this snazzy square brackets notation takes care of that, i'm happy to give it a try! i'll have a go :)

**Comment by ClareBee** [comment]
Had a chat with Peter - have moved the removeUserMarker() function so that it kicks in as the user chooses an alternative search bar result, clearing away the previous marker. we can always move it again if we decide tomorrow!

**Comment by PMGH** [comment]
Shall we merge?

**Comment by PMGH** [comment]
Looks good to me, had a play on the branch and it removes the old marker as you would expect. 👍

**Pull request merged**
